#web
server:
  port: 8080
# mybatis
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
  mapperLocations: mapper/**/*.xml
#  type-aliases-package:
#druid
spring:
  datasource:
    minIdle: 500
    validationQuery: select 'x'
    initialSize: 100
    maxWait: 60000
    filters: stat
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    password: 123456
    testOnBorrow: false
    maxOpenPreparedStatements: 20
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 1000
    username: root
  #rabbitmq
  rabbitmq:
    username: root
    password: root123
    port: 5672
    virtual-host: /
    host: 192.168.0.111
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true #是否支持重试
#redis
redis:
  host: 192.168.0.111
  port: 6379
  timeout: 3
  password: 123456
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500

#日志
logging:
  config: classpath:config/log4j2-dev.xml


